language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
script:
  - cargo build --verbose --all --features serialize,deserialize
  - cargo test --verbose --all --features serialize,deserialize
  - cargo build --verbose --all --features serialize
  - cargo test --verbose --all --features serialize
  - cargo build --verbose --all --features deserialize
  - cargo test --verbose --all --features deserialize
  - cargo build --verbose --all 
  - cargo test --verbose --all 
